project:
  type: website

website:
  title: "Prédiction d'incendies de forêt"
  navbar:
    left:
      - href: index.qmd
        text: Accueil

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



