apiVersion: apps/v1
kind: Deployment
metadata:
  name: incendies-deployment
  labels:
    app: incendies
spec:
  replicas: 1
  selector:
    matchLabels:
      app: incendies
  template:
    metadata:
      labels:
        app: incendies
    spec:
      containers:
      - name: incendies
        image: thomasroussaux/app-mise-en-prod:v0.0.1
        ports:
        - containerPort: 8000
        env:
        - name: JETON_API
          valueFrom:
            secretKeyRef:
              name: api-jeton
              key: JETON_API
        envFrom:
        - secretRef:
            name: s3-credentials